language: node_js
node_js:
  - 16

before_install:
  - pip install --upgrade pip
  - pip install awscli

install:
  - npm install

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: travispipeline
  local_dir: build
  acl: public_read
  skip_cleanup: true
  region: us-west-2
